[server]
hostname = {{ .Values.deployment.ingress.hostName | quote }}
node_ip = "$env{NODE_IP}"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
offset = {{ .Values.deploymentToml.server.offset | quote }}

[transport.https.properties]
proxyPort = 443
server = {{ .Values.deploymentToml.transport.https.properties.server | quote }}

[transport.https.sslHostConfig.properties]
protocols={{ .Values.deploymentToml.transport.https.sslHostConfig.properties.protocols | quote }}
ciphers={{ .Values.deploymentToml.transport.https.sslHostConfig.properties.ciphers | quote }}

[super_admin]
username = {{ .Values.deploymentToml.superAdmin.username | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
password = "$secret{SUPER-ADMIN-PASSWORD}"
{{- else }}
password = {{ .Values.deploymentToml.superAdmin.password | quote }}
{{- end }}
create_admin_account = {{ .Values.deploymentToml.superAdmin.createAdminAccount }}

[user_store]
type = {{ .Values.deploymentToml.userStore.type | quote }}

[database.identity_db]
type = {{ .Values.deploymentToml.database.identity.type | quote }}
url = {{ .Values.deploymentToml.database.identity.url | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
username = "$secret{IDENTITY-DB-USER-USERNAME}"
password = "$secret{IDENTITY-DB-USER-PASSWORD}"
{{- else }}
username = {{ .Values.deploymentToml.database.identity.username | quote }}
password = {{ .Values.deploymentToml.database.identity.password | quote }}
{{- end }}
{{- if .Values.deploymentToml.database.identity.poolOptions }}
[database.identity_db.pool_options]
{{- range $key, $value := .Values.deploymentToml.database.identity.poolOptions }}
{{ $key }} = {{ $value | quote }}
{{- end }}
{{- end }}

[database.shared_db]
type = {{ .Values.deploymentToml.database.shared.type | quote }}
url = {{ .Values.deploymentToml.database.shared.url | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
username = "$secret{REGISTRY-DB-USER-USERNAME}"
password = "$secret{REGISTRY-DB-USER-PASSWORD}"
{{- else }}
username = {{ .Values.deploymentToml.database.shared.username | quote }}
password = {{ .Values.deploymentToml.database.shared.password | quote }}
{{- end }}
{{- if .Values.deploymentToml.database.shared.poolOptions }}
[database.shared_db.pool_options]
{{- range $key, $value := .Values.deploymentToml.database.shared.poolOptions }}
{{ $key }} = {{ $value | quote }}
{{- end }}
{{- end }}

[keystore.tls]
file_name =  {{ .Values.deploymentToml.keystore.tls.fileName | quote }}
type =  {{ .Values.deploymentToml.keystore.tls.type | quote }}
alias = {{ .Values.deploymentToml.keystore.tls.alias | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
password = "$secret{INTERNAL-KEYSTORE-PASSWORD}"
key_password = "$secret{INTERNAL-KEYSTORE-PASSWORD}"
{{- else }}
password = {{ .Values.deploymentToml.keystore.internal.internalKeyStorePassword | quote }}
key_password = {{ .Values.deploymentToml.keystore.internal.internalKeyStorePassword | quote }}
{{- end }}

[keystore.primary]
file_name =  {{ .Values.deploymentToml.keystore.primary.fileName | quote }}
type =  {{ .Values.deploymentToml.keystore.primary.type | quote }}
alias = {{ .Values.deploymentToml.keystore.primary.alias | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
password = "$secret{PRIMARY-KEYSTORE-PASSWORD}"
key_password = "$secret{PRIMARY-KEYSTORE-PASSWORD}"
{{- else }}
password = {{ .Values.deploymentToml.keystore.primary.primaryKeyStorePassword | quote }}
key_password = {{ .Values.deploymentToml.keystore.primary.primaryKeyStorePassword | quote }}
{{- end }}

[keystore.internal]
file_name =  {{ .Values.deploymentToml.keystore.internal.fileName | quote }}
type =  {{ .Values.deploymentToml.keystore.internal.type | quote }}
alias = {{ .Values.deploymentToml.keystore.internal.alias | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
password = "$secret{INTERNAL-KEYSTORE-PASSWORD}"
key_password = "$secret{INTERNAL-KEYSTORE-PASSWORD}"
{{- else }}
password = {{ .Values.deploymentToml.keystore.internal.internalKeyStorePassword | quote }}
key_password = {{ .Values.deploymentToml.keystore.internal.internalKeyStorePassword | quote }}
{{- end }}

[truststore]
file_name =  {{ .Values.deploymentToml.truststore.fileName | quote }}
type =  {{ .Values.deploymentToml.truststore.type | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
password = "$secret{TRUSTSTORE-PASSWORD}"
{{- else }}
password = {{ .Values.deploymentToml.truststore.trustStorePassword | quote }}
{{- end }}

[account_recovery.endpoint.auth]
{{- if .Values.deployment.secretStore.azure.enabled }}
hash = "$secret{APPS-PASSWORD-HASH}"
{{- else }}
hash = {{ .Values.deploymentToml.account.recovery.endpoint.auth.hash | quote }}
{{- end }}

[identity.auth_framework.endpoint]
{{- if .Values.deployment.secretStore.azure.enabled }}
app_password = "$secret{APPS-PASSWORD}"
{{- else }}
app_password = {{ .Values.deploymentToml.identity.identityAppsPassword | quote }}
{{- end }}


{{- if .Values.deploymentToml.clustering.enabled }}
[clustering]
membership_scheme = "kubernetes"
domain = "wso2.carbon.domain"
properties.membershipSchemeClassName = "org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme"
properties.KUBERNETES_NAMESPACE = "{{ .Release.Namespace }}"
properties.KUBERNETES_SERVICES = {{ include "..fullname" . | quote }}
properties.KUBERNETES_MASTER_SKIP_SSL_VERIFICATION = "true"
properties.USE_DNS = "false"
{{- end }}

[oauth.token_cleanup]
enable = {{.Values.deploymentToml.oauth.tokenCleanup }}

[oauth.token_generation]
include_username_in_access_token = {{.Values.deploymentToml.oauth.tokenGeneration.includeUsernameInAccessToken }}

# Block all unused fileupload with super tenant permissions (SECURITYINTERNAL-1738)
[[resource.access_control]]
context="(.*)/fileupload/service(.*)"
secure=true
http_method = "all"
permissions = ["/permission/admin/manage/identity/applicationmgt/create"]

[[resource.access_control]]
context="(.*)/fileupload(.*)"
secure=true
http_method = "all"
permissions = ["/permission/protected/manage/monitor/tenants"]

{{- if .Values.deploymentToml.recaptcha.enabled }}
[recaptcha]
enabled = true
api_url = {{ .Values.deploymentToml.recaptcha.apiUrl | quote }}
verify_url = {{ .Values.deploymentToml.recaptcha.verifyUrl | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
site_key = "$secret{RECAPTCHA-SITE-KEY}"
secret_key = "$secret{RECAPTCHA-SECRET-KEY}"
{{- else }}
site_key = {{ .Values.deploymentToml.recaptcha.siteKey | quote }}
secret_key = {{ .Values.deploymentToml.recaptcha.secretKey | quote }}
{{- end }}
{{- end }}

{{- if .Values.deploymentToml.outputAdapter.email.enabled }}
# SMTP email sender settings.
[output_adapter.email]
from_address= {{ .Values.deploymentToml.outputAdapter.email.fromAddress | quote }}
username= {{ .Values.deploymentToml.outputAdapter.email.username | quote }}
{{- if .Values.deployment.secretStore.azure.enabled }}
password = "$secret{SMTP-PASSWORD}"
{{- else }}
password = {{ .Values.deploymentToml.outputAdapter.email.password | quote }}
{{- end }}
hostname= {{ .Values.deploymentToml.outputAdapter.email.hostname | quote }}
port= {{ .Values.deploymentToml.outputAdapter.email.port }}
enable_start_tls= {{ .Values.deploymentToml.outputAdapter.email.enableStartTls }}
enableAuthentication= {{ .Values.deploymentToml.outputAdapter.email.enableAuthentication }}
{{- end }}

# Configuring user account locking. Ref: https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/lock-account/
{{- if .Values.deploymentToml.userAccountLock.enabled }}
[event.default_listener.identity_mgt]
priority= "50"
enable = false
[event.default_listener.governance_identity_mgt]
priority= "95"
enable = true

[identity_mgt.account_locking]
allowed_failed_attempts={{ .Values.deploymentToml.userAccountLock.loginAttempts.allowedFailedAttempts }}
auto_unlock_time_increment_ratio={{ .Values.deploymentToml.userAccountLock.loginAttempts.autoUnlockTimeIncrementRatio }}
auto_unlock_after={{ .Values.deploymentToml.userAccountLock.loginAttempts.autoUnlockAfter }}
enable_account_locking=true

{{- end }}

[authentication.authenticator.email_otp]
enable={{ .Values.deploymentToml.otp.email.enabled }}

[authentication.authenticator.email_otp.parameters]
EMAILOTPAuthenticationEndpointURL = {{ .Values.deploymentToml.otp.email.authenticationEndpointURL | quote }}
EmailOTPAuthenticationEndpointErrorPage = {{ .Values.deploymentToml.otp.email.authenticationEndpointErrorPage | quote }}
EmailAddressRequestPage = {{ .Values.deploymentToml.otp.email.addressRequestPage | quote }}
usecase = {{ .Values.deploymentToml.otp.email.usecase | quote }}
secondaryUserstore = {{ .Values.deploymentToml.otp.email.secondaryUserstore | quote }}
EMAILOTPMandatory = {{ .Values.deploymentToml.otp.email.mandatory }}
sendOTPToFederatedEmailAttribute = {{ .Values.deploymentToml.otp.email.sendOTPToFederatedEmailAttribute }}
federatedEmailAttributeKey = {{ .Values.deploymentToml.otp.email.federatedEmailAttributeKey | quote }}
EmailOTPEnableByUserClaim = {{ .Values.deploymentToml.otp.email.enableByUserClaim }}
CaptureAndUpdateEmailAddress = {{ .Values.deploymentToml.otp.email.captureAndUpdateEmailAddress }}
showEmailAddressInUI = {{ .Values.deploymentToml.otp.email.showEmailAddressInUI }}
useEventHandlerBasedEmailSender = {{ .Values.deploymentToml.otp.email.useEventHandlerBasedEmailSender }}
emailAddressRegex = {{ .Values.deploymentToml.otp.email.emailAddressRegex | squote }}
tokenExpirationTime = {{ .Values.deploymentToml.otp.email.tokenExpirationTime }}
EnableAccountLockingForFailedAttempts = {{ .Values.deploymentToml.otp.email.userAccountLockEnabled }}

[authentication.authenticator.sms_otp]
enable={{ .Values.deploymentToml.otp.sms.enabled }}

[authentication.authenticator.sms_otp.parameters]
SMSOTPAuthenticationEndpointURL= {{ .Values.deploymentToml.otp.sms.authenticationEndpointURL | quote }}
SMSOTPAuthenticationEndpointErrorPage= {{ .Values.deploymentToml.otp.sms.authenticationEndpointErrorPage | quote }}
MobileNumberRegPage = {{ .Values.deploymentToml.otp.sms.mobileNumberRegPage | quote }}
RetryEnable = {{ .Values.deploymentToml.otp.sms.retryEnable }}
ResendEnable = {{ .Values.deploymentToml.otp.sms.resendEnable }}
BackupCode = {{ .Values.deploymentToml.otp.sms.backupCode }}
SMSOTPEnableByUserClaim = {{ .Values.deploymentToml.otp.sms.enableByUserClaim }}
usecase = {{ .Values.deploymentToml.otp.sms.usecase | quote }}
secondaryUserstore = {{ .Values.deploymentToml.otp.sms.secondaryUserstore | quote }}
SMSOTPMandatory = {{ .Values.deploymentToml.otp.sms.mandatory }}
SendOtpToFederatedMobile = {{ .Values.deploymentToml.otp.sms.federatedMobile  }}
federatedMobileAttributeKey = {{ .Values.deploymentToml.otp.sms.federatedMobileAttributeKey | quote }}
CaptureAndUpdateMobileNumber = {{ .Values.deploymentToml.otp.sms.captureAndUpdateMobileNumber }}
SendOTPDirectlyToMobile = {{ .Values.deploymentToml.otp.sms.directlyToMobile }}
redirectToMultiOptionPageOnFailure = {{ .Values.deploymentToml.otp.sms.redirectToMultiOptionPageOnFailure }}
EnableAccountLockingForFailedAttempts = {{ .Values.deploymentToml.otp.sms.userAccountLockEnabled }}

[authentication.authenticator.totp]
enable={{ .Values.deploymentToml.totp.enabled }}

[authentication.authenticator.totp.parameters]
encodingMethod={{ .Values.deploymentToml.totp.encodingMethod | quote }}
timeStepSize={{ .Values.deploymentToml.totp.timeStepSize | quote }}
windowSize={{ .Values.deploymentToml.totp.windowSize | quote }}
authenticationMandatory={{ .Values.deploymentToml.totp.authenticationMandatory }}
enrolUserInAuthenticationFlow={{ .Values.deploymentToml.totp.enrolUserInAuthenticationFlow }}
usecase={{ .Values.deploymentToml.totp.usecase | quote }}
secondaryUserstore={{ .Values.deploymentToml.totp.secondaryUserstore | quote }}
TOTPAuthenticationEndpointURL={{ .Values.deploymentToml.totp.authenticationEndpointURL | quote }}
TOTPAuthenticationEndpointErrorPage={{ .Values.deploymentToml.totp.authenticationEndpointErrorPage | quote }}
TOTPAuthenticationEndpointEnableTOTPPage={{ .Values.deploymentToml.totp.authenticationEndpointEnableTOTPPage | quote }}
Issuer={{ .Values.deploymentToml.totp.issuer | quote }}
UseCommonIssuer={{ .Values.deploymentToml.totp.useCommonIssuer }}
EnableAccountLockingForFailedAttempts = {{ .Values.deploymentToml.totp.userAccountLockEnabled }}

{{- if .Values.deploymentToml.extraConfigs }}
{{ .Values.deploymentToml.extraConfigs }}
{{- end }}
