# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------
{{- if .Values.deployment.secretStore.azure.enabled }}
apiVersion: {{ .Values.k8sKindAPIVersions.secretProviderClass }}
kind: SecretProviderClass
metadata:
  name: {{ template "..fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    userAssignedIdentityID: "{{ .Values.deployment.secretStore.azure.keyVault.servicePrincipalAppID }}"
    keyvaultName: "{{ .Values.deployment.secretStore.azure.keyVault.name }}"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: INTERNAL-KEYSTORE-PASSWORD-DECRYPTED
          objectType: secret
          objectVersion: ""
    tenantId: "{{ .Values.deployment.secretStore.azure.keyVault.tenantId }}"
    resourceGroup: "{{ .Values.deployment.secretStore.azure.keyVault.resourceGroup }}"
    subscriptionId: "{{ .Values.deployment.secretStore.azure.keyVault.subscriptionId }}"
{{- end }}
